version: '3'

services:
    mysql:
        image: yappabe/mysql:5.7
        environment:
            DNSDOCK_ALIAS: mysql.symfarticles.docker.webfolks.be
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: dev
            MYSQL_DATABASE: symf_articles

volumes:
    mysql-data:
