version: '3'

services:
    nginx:
        image: yappabe/nginx:1.9
        volumes:
            - ./:/var/www/app
        depends_on:
            - php
        environment:
            DNSDOCK_ALIAS: symfarticles.docker.webfolks.be
            DOCUMENT_ROOT: /var/www/app/public
            INDEX_FILE: index.php
            PHP_FPM_SOCKET: php:9000
    mysql:
        image: yappabe/mysql:5.7
        environment:
            DNSDOCK_ALIAS: mysql.symfarticles.docker.webfolks.be
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: dev
            MYSQL_DATABASE: symf_articles
    php:
        image: yappabe/php:7.3
        volumes:
            - ./:/var/www/app
            - vendor:/vendor
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
            - ~/.composer:/root/.composer
            - /tmpfs
        working_dir: /var/www/app
        environment:
            PHP_FPM_USER: root
        depends_on:
            - mysql

volumes:
    mysql-data:
    vendor:
